repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.761'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--follow-imports=skip]